name: CI

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      - name: Compress Build
        run: |
          tar -cJf dist.tar.xz dist/

      - name: Set Tag
        run: |
          git tag $(git rev-parse --short HEAD)
          git push $(git rev-parse --short HEAD)

      - name: Release
        run: |
          gh release create $(git rev-parse --short HEAD) dist.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
