name: CI

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      - name: Compress Build
        run: |
          tar -cJf dist.tar.xz dist/

      - name: Get Tag Name
        run: echo "TAG_NAME=$(date +'v%H%M%S%Y%m%d')" >> $GITHUB_ENV

      - name: Set Tag
        run: |
          git tag $TAG_NAME
          git push $TAG_NAME

      - name: Release
        run: |
          gh release create $TAG_NAME dist.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
